name: build

on:
  release:
    types:
      - "published"

jobs:
  build-app-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/scmtble/zhifou-app-api:latest,registry.cn-hangzhou.aliyuncs.com/scmtble/zhifou-app-api:${{ env.RELEASE_VERSION }}

  build-user-rpc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./user
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/scmtble/zhifou-user-rpc:latest,registry.cn-hangzhou.aliyuncs.com/scmtble/zhifou-user-rpc:${{ env.RELEASE_VERSION }}

  build-dynamic-rpc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./dynamic
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/scmtble/zhifou-dynamic-rpc:latest,registry.cn-hangzhou.aliyuncs.com/scmtble/zhifou-dynamic-rpc:${{ env.RELEASE_VERSION }}

  build-tag-rpc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./tag
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/scmtble/zhifou-tag-rpc:latest,registry.cn-hangzhou.aliyuncs.com/scmtble/zhifou-tag-rpc:${{ env.RELEASE_VERSION }}
